# Project info
sonar.organization=vws
sonar.projectKey=nl-uzi-yivi-disclosure-web-private
sonar.projectName=nl-uzi-yivi-disclosure-web-private

# Info links shown in SonarCloud
sonar.links.homepage=https://github.com/minvws/nl-uzi-yivi-disclosure-web-private

# Encoding and language specific properties
sonar.sourceEncoding=UTF-8

# Analysis scoping
sonar.sources=app,bootstrap,config,public,resources,routes
sonar.tests=tests

# Code coverage
sonar.php.tests.reportPath=
sonar.php.coverage.reportPaths=
sonar.coverage.exclusions=

# Duplication exclusions
sonar.cpd.exclusions=

# Additional reports
sonar.php.phpstan.reportPaths=
