name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

env:
  CURRENTLY_USED_PHP_VERSION: '8.3'

jobs:
  validate_npm:
    name: Build & validate npm
    runs-on: ubuntu-24.04
    env:
      node_version: '22'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm audit
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}
      - run: npm run build

  validate_php:
    name: Validate PHP
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php_version: [ '8.3', '8.4' ]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/cache@v5
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: zip, xdebug
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate _ide_helper file
        run: php artisan ide-helper:generate
      - name: Static analysis with Psalm
        run: vendor/bin/psalm
      - name: Coding style PSR12 Check
        run: vendor/bin/phpcs
      - name: Copy .env
        run: cp -n .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Create reports directory
        run: mkdir -p reports
      - name: Static analysis with PHPStan
        run: vendor/bin/phpstan analyse --error-format=json --no-ansi > reports/phpstan.json
      - name: Check for known CVE vulnerabilities
        run: php artisan security-check:now
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature)
        run: vendor/bin/phpunit --log-junit=reports/report-phpunit.xml --coverage-clover=reports/coverage-phpunit.xml
      - name: Run SonarQube scan
        if: ${{ matrix.php_version == env.CURRENTLY_USED_PHP_VERSION }}
        uses: minvws/action-sonarqube@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
